#!/usr/bin/env python
# -*- coding: utf-8 -*-
"""
Inventory Error Report Collector

This script lists recent inventory error reports and prints previews of their content.
Error reports are generated by modules/inventory_lines_dialog.py when inventory
loading fails.

Usage:
    python scripts/collect_inventory_error_reports.py

The script will:
1. Find all reports/inventory_error_*.txt files
2. Sort them by timestamp (newest first)
3. Display a preview of each report

Note: Error reports are not committed to the repository (excluded in .gitignore).
"""

import os
import glob
import itertools
from datetime import datetime


def collect_and_preview_reports(reports_dir="reports", max_preview_lines=30):
    """
    Collect and preview inventory error reports.
    
    Args:
        reports_dir: Directory containing error reports (default: "reports")
        max_preview_lines: Maximum number of lines to show per report (default: 30)
    """
    # Resolve reports directory path
    script_dir = os.path.dirname(os.path.abspath(__file__))
    repo_root = os.path.dirname(script_dir)
    reports_path = os.path.join(repo_root, reports_dir)
    
    # Check if reports directory exists
    if not os.path.exists(reports_path):
        print(f"Reports directory not found: {reports_path}")
        print("No error reports have been generated yet.")
        return
    
    # Find all inventory error reports
    report_pattern = os.path.join(reports_path, "inventory_error_*.txt")
    report_files = glob.glob(report_pattern)
    
    if not report_files:
        print(f"No inventory error reports found in: {reports_path}")
        print("This is good news - no errors have been reported!")
        return
    
    # Sort reports by modification time (newest first)
    report_files.sort(key=lambda f: os.path.getmtime(f), reverse=True)
    
    print("=" * 80)
    print(f"INVENTORY ERROR REPORT SUMMARY")
    print("=" * 80)
    print(f"Reports directory: {reports_path}")
    print(f"Total reports found: {len(report_files)}")
    print("=" * 80)
    print()
    
    # Display each report
    for idx, report_file in enumerate(report_files, start=1):
        filename = os.path.basename(report_file)
        file_size = os.path.getsize(report_file)
        file_mtime = datetime.fromtimestamp(os.path.getmtime(report_file))
        
        print(f"\n{'=' * 80}")
        print(f"REPORT {idx}/{len(report_files)}: {filename}")
        print(f"Modified: {file_mtime.strftime('%Y-%m-%d %H:%M:%S')}")
        print(f"Size: {file_size} bytes")
        print(f"{'=' * 80}")
        
        # Read and display preview
        try:
            with open(report_file, 'r', encoding='utf-8') as f:
                # Use islice to read only needed lines for memory efficiency
                preview_lines = list(itertools.islice(f, max_preview_lines))
                
                print('\n'.join(line.rstrip() for line in preview_lines))
                
                # Check if there are more lines by trying to read one more
                next_line = f.readline()
                if next_line:
                    print(f"\n... (more lines, file continues)")
                    print(f"\nFull report: {report_file}")
        
        except Exception as e:
            print(f"Error reading report: {e}")
    
    print("\n" + "=" * 80)
    print("END OF REPORT SUMMARY")
    print("=" * 80)


def main():
    """Main entry point for the script."""
    print("Inventory Error Report Collector")
    print("=" * 80)
    print()
    
    collect_and_preview_reports()
    
    print("\n")
    print("Note: These reports help diagnose inventory loading issues.")
    print("See docs/DIAGNOSTICS_INVENTORY.md for more information.")


if __name__ == "__main__":
    main()
